BATCH_SIZE: 24
IMAGE_SIZE: 640
EPOCHS: 200
WORKERS: 4
MODEL: yolo26s-pose.pt
NAME: "YOLO26SMALL_MULTISCALE#0.25&LRF#0.005"
#___#
MULTI_SCALE: 0.25 # DEFAULT
WARMUP_EPOCHS: 3 # DEFAULT
MOMENTUM: 0.937 # DEFAULT
LR0: 0.01
LRF: 0.005
FREEZE: ~ # DEFAULT
COS_LR: False # DEFAULT
SEED: 42
PRETRAINED: True # DEFAULT
OPTIMIZER: "MuSGD"