BATCH_SIZE: 48
IMAGE_SIZE: 640
EPOCHS: 100
WORKERS: 4
MODEL: yolo26n-pose.pt
NAME: "YOLO26NANO_LR0$0.015LRF$0.004"
#___#
MULTI_SCALE: 0.0 # DEFAULT
WARMUP_EPOCHS: 10 # DEFAULT
MOMENTUM: 0.937 # DEFAULT
LR0: 0.015
LRF: 0.004
FREEZE: ~ # DEFAULT
COS_LR: True # DEFAULT
SEED: 42
PRETRAINED: True # DEFAULT
OPTIMIZER: "MuSGD"