BATCH_SIZE: 48
IMAGE_SIZE: 640
EPOCHS: 100
WORKERS: 4
MODEL: yolo26n-pose.pt
NAME: "YOLO26NANO_MULTISCALE#0.25&FREEZE#10"
#___#
MULTI_SCALE: 0.25
WARMUP_EPOCHS: 5 # DEFAULT
MOMENTUM: 0.937 # DEFAULT
LR0: 0.01
LRF: 0.01
FREEZE: 10
COS_LR: False # DEFAULT
SEED: 42
PRETRAINED: True # DEFAULT
OPTIMIZER: "MuSGD"